import Head from "next/head";
import Script from "next/script";
import { EmblaOptionsType } from "embla-carousel-react";

import styles from "../styles/Home.module.css";

import Carousel from "../components/Carousel";

export default function Home() {
  const OPTIONS: EmblaOptionsType = {};
  const SLIDE_COUNT = 3;
  const SLIDES = Array.from(Array(SLIDE_COUNT).keys());
  return (
    <>
      <Head>
        <title>Pat`&apos;`s BBQ Train</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="<https://app.snipcart.com>" />
        <link rel="preconnect" href="<https://cdn.snipcart.com>" />
        <link rel="shortcut icon" href="../public/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div
          hidden
          id="snipcart"
          data-api-key="YWIwNzE5ZjYtMGE0Mi00YTc3LTgzNjQtZDg5ZDg5YTEzOWNjNjM3MjYyMDkxNzk5NzgwNzY2"
        ></div>
        <Carousel slides={SLIDES} options={OPTIONS} />
      </main>
      <Script src="https://cdn.snipcart.com/themes.v3.2.0/default/snipcart.js" />
    </>
  );
}
